MREGodotRuntime/Scenes/Player.tscn, MREGodotRuntime/Scenes/Standalone.tscn, MREGodotRuntime/Scripts/DialogFactory.cs, MREGodotRuntime/Scripts/LaunchMRE.cs, MREGodotRuntime/Scripts/MREComponent.cs, MREGodotRuntimeLib/API/MREApi.cs, MREGodotRuntimeLib/App/MixedRealityExtensionApp.cs, MREGodotRuntimeLib/PluginInterfaces/IDialogFactory.cs
There are two types of Dialog.
1. Without TextEdit.
2. With TextEdit.
However, TextEdit won't work because there is no virtual keyboard in mre-godot.
=> add Dialog

MREGodotRuntimeLib/Core/Actor.cs
This patch will fix kinematic body position issue in physics-dynamic-vs-kinematic test.
=> flip rigidbody transform z axis

MREGodotRuntime/Scripts/Behaviors/BehaviorFactory.cs, MREGodotRuntime/Scripts/Behaviors/ToolkitButtonBehavior.cs, MREGodotRuntime/Scripts/Tools/ToolkitButtonTool.cs, MREGodotRuntimeLib/Behaviors/ActionData/ToolkitButtonData.cs, MREGodotRuntimeLib/Behaviors/Behaviors.cs, MREGodotRuntimeLib/Behaviors/Contexts/BehaviorContextFactory.cs, MREGodotRuntimeLib/Behaviors/Contexts/ToolkitButtonBehaviorContext.cs, MREGodotRuntimeLib/Core/Actor.cs, MREGodotRuntimeLib/PluginInterfaces/Behaviors/IBehaviorFactory.cs, MREGodotRuntimeLib/PluginInterfaces/Behaviors/IToolkitButtonBehavior.cs, Toolkit/PressableButtonGodot.cs
1. add ToolkitButtonBehavior and related classes
2. link ToolkitButtonBehavior to PressableButton
=> add ToolkitButtonBehavior

MREGodotRuntime/Scripts/Tools/TargetTool.cs
It might be useful for updating internal events.
=> add a method to TargetTool that is called when the target point is updated

MREGodotRuntime/Scripts/Tools/ButtonTool.cs, Toolkit/IMixedRealityPointerHandler.cs, Toolkit/MixedRealityPointerEventData.cs
The ButtonTool is one of Tools that triggers pointer events.
=> emit pointer event when button tool is updated

MREGodotRuntime/Scripts/Player/InputSource.cs, MREGodotRuntime/Scripts/Tools/SphereTool.cs, MREGodotRuntime/Scripts/Tools/TargetTool.cs, addons/godot-openxr/scenes/MRTK_R_Hand.tscn
The SphereTool can trigger near pointer event with NearInteractionGrabbable.
=> add Sphere Tool

MREGodotRuntime/Scripts/Player/InputSource.cs
This will fix toolkit button visibility issue.
=> restore proximity visible light

Toolkit/PressableButtonGodot.cs, Toolkit/PressableButtonGodot.tscn
The size of the mrtk-unity button is 32x32mm..!
=> change toolkit button default size from 64x64mm to 32x32mm

MREGodotRuntime/Scenes/Player.gd, MREGodotRuntime/Scenes/Player.tscn, MREGodotRuntime/Scripts/Player/InputSource.cs
We can move the right hand with shift key.
=> move the hand with shift key

MREGodotRuntime/Scripts/Tools/PokeTool.cs, MREGodotRuntime/Scripts/Tools/TargetTool.cs, MREGodotRuntime/Scripts/Tools/Tool.cs, MREGodotRuntimeLib/App/MixedRealityExtensionApp.cs, MREGodotRuntimeLib/Assets/AssetLoader.cs, MREGodotRuntimeLib/Messaging/Payloads/AssetCommandPayloads.cs, MREGodotRuntimeLib/Messaging/Payloads/PayloadTypeRegistry.cs, MREGodotRuntimeLib/Util/Godot/MWGodotHelpers.cs, Toolkit/ClippingBox.cs, Toolkit/ScrollingObjectCollection.cs, Toolkit/ScrollingObjectCollection.tscn
`ScrollingObjectCollection.cs` is from mrty-unity.
=> add scrolling object collection

MREGodotRuntimeLib/Core/Actor.cs, Toolkit/PressableButtonGodot.cs, Toolkit/ScrollingObjectCollection.cs, Toolkit/TogglePressableButtonGodot.cs
The actor properties will be set from server side.
=> cleanup toolkit applypatch

MREGodotRuntimeLib/Animation/AnimationManager.cs, MREGodotRuntimeLib/Animation/Interpolations.cs, MREGodotRuntimeLib/Animation/JTokenPool.cs, MREGodotRuntimeLib/Assets/AssetLoader.cs, MREGodotRuntimeLib/Assets/Definitions.cs, MREGodotRuntimeLib/Factories/DefaultMaterialPatcher.cs, MREGodotRuntimeLib/Patching/Types/ColorPatch.cs, MREGodotRuntimeLib/Patching/Types/MaterialPatch.cs, MREGodotRuntimeLib/PluginInterfaces/IMaterialPatcher.cs
Material color can be used as animation data.
=> add support for color animation

MREGodotRuntimeLib/Core/Actor.cs, MREGodotRuntimeLib/Patching/PatchingUtils.cs, MREGodotRuntimeLib/Util/Godot/MWGodotTypeExtensions.cs, MREGodotRuntimeLib/Util/TransformLerper.cs
1. fix axis issue between godot and mre coord system.
2. use `RotationQuat()` instead of `new Quat()` that returns the basis's rotation with scale factor.
we shouldn't use rotation with scale because we use separate scale
property.
=> fix transform issue.

MREGodotRuntimeLib/Core/TouchablePlane.cs
`ToGlobal()` transforms the position, rotation and scale from local space
to global space.
but, we should transform only rotation of local forward here.
=> TouchablePlane: change only rotation of local forward to global coord

MREGodotRuntime/Scripts/Player/InputSource.cs, MREGodotRuntime/Scripts/Tools/ButtonTool.cs, MREGodotRuntime/Scripts/Tools/PokeTool.cs, MREGodotRuntime/Scripts/Tools/TargetTool.cs
1. rename CollisionPoint to Cursor.
2. move the method that updates cursor position form TargetTool to InputSource.
=> move cursor update method to InputSource

MREGodotRuntime/Scripts/Player/InputSource.cs, MREGodotRuntime/Scripts/Tools/ButtonTool.cs, MREGodotRuntime/Scripts/Tools/TargetTool.cs
HMD doesn't have 'left mouse button'.
=> trigger button tool event with pinch gesture

MREGodotRuntimeLib/Assets/AssetLoader.cs
The collider for gltf meshes was added from the old gltf loader.
however, new gltf loader no longer generate the colliders. so, we need generate it on loading gltf.
=> add collider for gltf meshes

Toolkit/ActionData/ActionData.cs, Toolkit/ActionData/ToolkitAction.cs, Toolkit/PinchSlider.cs, Toolkit/PressableButton.cs, Toolkit/PressableButtonGodot.cs, Toolkit/ScrollingObjectCollection.cs, Toolkit/TogglePressableButtonGodot.cs
Add toolkit action that connect to mre event.
=> toolkit: add new classes for toolkit aciton and events for toolkit 

MREGodotRuntime/Scenes/DefaultRightHand.tscn, MREGodotRuntime/Scenes/Player.tscn, MREGodotRuntime/Scenes/Ray.tscn, MREGodotRuntime/Scenes/RingCursor.tscn, MREGodotRuntime/Scenes/Standalone.tscn, MREGodotRuntime/Scripts/Controls/Controllers/BaseController.cs, MREGodotRuntime/Scripts/Controls/Controllers/HandController.cs, MREGodotRuntime/Scripts/Controls/Controllers/IController.cs, MREGodotRuntime/Scripts/Controls/MouseController.cs, MREGodotRuntime/Scripts/Controls/PositionControls/IPositionControl.cs, MREGodotRuntime/Scripts/Controls/PositionControls/KeyboardPositionControl.cs, MREGodotRuntime/Scripts/Controls/PositionControls/VirtualGamepadPositionControl.cs, MREGodotRuntime/Scripts/Controls/RotationControls/IRotationControl.cs, MREGodotRuntime/Scripts/Controls/RotationControls/MouseRotationControl.cs, MREGodotRuntime/Scripts/DefaultScenePath.cs, MREGodotRuntime/Scripts/ExportEnumAttribute.cs, MREGodotRuntime/Scripts/Joystick2D.cs, MREGodotRuntime/Scripts/LaunchMRE.cs, MREGodotRuntime/Scripts/Player.cs, MREGodotRuntime/Scripts/Player/Cursor.cs, MREGodotRuntime/Scripts/Player/DefaultRightHand.cs, MREGodotRuntime/Scripts/Player/InputSource.cs, MREGodotRuntime/Scripts/Player/MainCamera.cs, MREGodotRuntime/Scripts/Player/Ray.cs, MREGodotRuntime/Scripts/Tools/ButtonTool.cs, MREGodotRuntime/Scripts/Tools/GrabTool.cs, MREGodotRuntime/Scripts/Tools/PokeTool.cs, MREGodotRuntime/Scripts/Tools/TargetTool.cs
- runtime: make cursor a separate scene
- runtime: make ray a separate scene
- runtime: change user node from ARVROrigin to ARVRCamera
- runtime: introduce Position Control
- runtime: introduce Rotation Control
- runtime: introduce Controller
- runtime: add mouse controller
=> runtime: refactoring player input

Toolkit/PinchSlider.cs, Toolkit/ScrollingObjectCollection.cs
Instead, it uses IActor interface.
=> toolkit: remove actor dependency

MREGodotRuntimeLibUnitTests/.gitignore, MREGodotRuntimeLibUnitTests/MREGodotRuntimeLibUnitTests.csproj, MREGodotRuntimeLibUnitTests/MREGodotRuntimeLibUnitTests.sln, MREGodotRuntimeLibUnitTests/Main.cs, MREGodotRuntimeLibUnitTests/Main.tscn, MREGodotRuntimeLibUnitTests/TestFilter.cs, MREGodotRuntimeLibUnitTests/TestListener.cs, MREGodotRuntimeLibUnitTests/TestTemplate.cs, MREGodotRuntimeLibUnitTests/project.godot, mixed-reality-extension-godot.csproj
How to run unit test
1. open godot project(`MREGodotRuntimeLibUnitTests/project.godot`)
2. run Main.tscn
=> test: add unit test project and template

MREGodotRuntime/Scripts/MREComponent.cs
Since drawing app is not public application, this removes the code related to it
=> runtime: remove some code related to internal

MREGodotRuntimeLib/Assets/AssetLoader.cs
prefabs should contain all nodes, not just root nodes.
=> lib: fix issue where some nodes aren't saved in assets

MREGodotRuntimeLib/Core/ClippingBase.cs
This patch is relevant to `AssetLoader.CreateFromPrefab`.
In this method, the types of nodes change to `Actor` type regardless of what type
they were before. The reason of that is related to godot C# binding. refer to
godot github issue for more information.
(https://github.com/godotengine/godot/issues/31994#issuecomment-570073343)
In `ClippingBase`, this causes problems taht type-testing operator to check if
the node is `MeshInstance` gives unexpected result because the node that was
`MeshInstance` before and has `Actor` scripts is no longer `MeshInstance` type.
So we use `Spatial` instead of `MeshInstance` for type-testing since `Actor` is
`Spatial` type.
=> lib: change MeshInstance type-testing to Spatial in ClippingBase

MREGodotRuntimeLib/Assets/AssetLoader.cs, MREGodotRuntimeLib/Core/Actor.cs
It creates fewer nodes than before.
=> minor optimization for gltf

MREGodotRuntimeLib/API/MREApi.cs, MREGodotRuntimeLib/MREPlugin.cs
We can write mre plugin with this class.
See the following sample to implement the mre plugin.
```cs
public class MyMREPlugin : MREPlugin
{
public MyMREPlugin(IMixedRealityExtensionApp app) : base(app)
{
TypeRegistry = typeof(MyPayloadTypeRegistry);
JsonConverters = new List<JsonConverter>() {
new MyPatchConverter(),
};
}
[CommandHandler(typeof(CreateMyObject))]
private void OnCreateMyObject(CreateMyObject payload, Action onCompleteCallback)
{
// ..
}
}
[PayloadType(typeof(CreateMyObject), "create-my-object")]
public class MyPayloadTypeRegistry { }
public class MyPatchConverter : JsonConverter
{
public override bool CanConvert(Type objectType)
{
return objectType == typeof(MyPatch);
}
public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer …
```
=> introduce MREPlugin class

MREGodotRuntimeLib/Core/Actor.cs, MREGodotRuntimeLib/Core/Light.cs
Since Godot4.0, the Lights seem brighter than before. so, lower Intensity has
been applied. And spot light had wrong angle and fixes that.
=> fix some issues on lights
