- MREGodotRuntimeLib/Assets/AssetLoader.cs
- MREGodotRuntimeLib/Core/Actor.cs
- MREGodotRuntimeLib/Core/ColliderGeometry.cs
In Godot, `BoxShape.Extents` means 'half extents'. but mre is not.
So, we need to apply half of value to the Extents.
See also, Godot Document of `BoxShape.Extents`:
```
The box's half extents. The width, height and depth of this shape is
twice the half extents.
```
> collider: adjust box collider size

- Toolkit/IMixedRealityEventHandler.cs
The internal event will bubble up to search the parent Node if
no Node matching the desired interface are found on the current Node.
> change the logic to change internal evnet handler

- MREGodotRuntime/Scripts/Tools/ButtonTool.cs
- MREGodotRuntime/Scripts/Tools/PokeTool.cs
- MREGodotRuntime/Scripts/Tools/SphereTool.cs
- MREGodotRuntime/Scripts/Tools/TargetTool.cs
- Toolkit/EventHandlerExtensions.cs
- Toolkit/IMixedRealityEventHandler.cs
- Toolkit/IMixedRealityFocusHandler.cs
- Toolkit/IMixedRealityPointerHandler.cs
- Toolkit/IMixedRealityTouchHandler.cs
- Toolkit/InputEventData.cs
- Toolkit/PinchSlider.cs
- Toolkit/PressableButton.cs
- Toolkit/PressableButtonGodot.cs
This patch fixes event bubbling issue. even if the child object handles the
event, it should be propagated to the parent object.
new parents class called Godot.Object is introduced for InputEventData because
only the Godot.Variant type is accepted as signal arguments in Godot Signal System.
> refactoring internal event system

- Toolkit/PressableButtonGodot.cs
The materials can be changed in runtime.
It uses getter to avoid unexpected issue.
> button: use getter for material property

- MREGodotRuntimeLib/Core/Components/ClippingComponent.cs
When the material is `SpatialMaterial`, we need to wait for shader compilation.
If `Process()` is called before the shader complilation, MaterialOverride will
throw invalid cast exception. to avoid exception, this patch adds type checking
condition.
> toolkit: fix invalid cast exception in clipping component

- MREGodotRuntime/Scripts/Tools/PokeTool.cs
PokeTool was only working on objects with (0, 0, 0) translation.
This patch fixes this issue :)
> fix raycast destination coordinates in PokeTool

- MREGodotRuntimeLib/Core/Actor.cs
- MREGodotRuntimeLib/Core/Components/MREAttachmentComponent.cs
Changing the parent of an actor can cause sync issues between clients.
To avoid this, use RemoteTrasform instead.
> use RemoteTransform instead of changing the parent for attachment

- MREGodotRuntime/Scripts/Tools/ButtonTool.cs
- MREGodotRuntime/Scripts/Tools/TargetTool.cs
If the raycast doesn't find a target while the button is pressed, the
button tool event doesn't work.
To fix this issue, hold the current target before button is released.
> hold current target on button tool pressed

- MREGodotRuntime/Scripts/Tools/PokeTool.cs
- Toolkit/HighlightArea.cs
- Toolkit/PressableButtonGodot.cs
- Toolkit/PressableButtonGodot.tscn
- remove `origin`, `backward` uniform to reduce coupling between cs and
shader
- fix pulse visual
- fix a issue that the closest normal was wrong in poke pointer
> toolkit: Simplify button code

- MREGodotRuntimeLib/Core/Actor.cs
When a gltf actor creatation is delayed, its child actors have no parent.
After gltf actor is created, we need to reset the parent of child.
> actor: ensure actor has correct parent

- MREGodotRuntimeLib/Assets/AssetLoader.cs
turn on anisotropic filtering by default for improved texture rendering result.
> asset: turn on anisotropic filtering by default

- MREGodotRuntimeLib/Assets/AssetFetcher.cs
The 3xx return code is not a failure.
Now, we can load properly cached web resources.
> fix web request failure condition

- MREGodotRuntimeLib/Patching/PatchingUtils.cs
-1 must be multiplied before transforming to the global coordinate system.
> Fix the logic to convert to the mre coordinate system of the app transform

- MREGodotRuntimeLib/Core/Actor.cs
- MREGodotRuntimeLib/Core/Components/MREAttachmentComponent.cs
When the server is not at the zero position, the RemoteTransform doesn't
work as expected.(it doesn't seem to respect rotation.)
The transform of attachment will be updated manually in `_process()`.
> override _process instead of inheriting RemoteTrasnform to update attachment

- MREGodotRuntimeLib/Messaging/Commands/CommandManager.cs
`DateTiem.Now` crashes on Android.
> commandmanager: replace DateTime.Now with Godot.OS.GetTicksMsec

- MREGodotRuntime/Scenes/Player.tscn
- MREGodotRuntime/Scenes/Standalone.tscn
- MREGodotRuntime/Scripts/Player.cs
- MREGodotRuntime/arvr_env.tres
Instead, it uses Environment property of MainCamera node.
> runtime: remove Environment node from standalon scene

- MREGodotRuntime/Scripts/LaunchMRE.cs
A object instance in the editor is different from the object instance in
the runtime. when we check area property, it's always different.
so, it uses `FindNode` instead of instance property.
> runtime: fix duplicated area node on trigger volume launch type

- MREGodotRuntime/Scripts/MREComponent.cs
`permissionManager` is assigned from `MREAPI.InitializeAPI`.
> runtime: remove unused code

- MREGodotRuntimeLib/Core/Actor.cs
- MREGodotRuntimeLib/Core/ClippingBase.cs
- MREGodotRuntimeLib/Core/ClippingBox.cs
- MREGodotRuntimeLib/Core/TouchablePlane.cs
- MREGodotRuntimeLib/PluginInterfaces/ITouchableSurface.cs
- Toolkit/PressableButtonGodot.cs
- Toolkit/ScrollingObjectCollection.cs
Since `ActorComponent` is internal, we cannot use it in toolkit package. instead, use public interfaces.
> toolkit: remove internal component dependencies

- Toolkit/PressableButtonGodot.cs
- Toolkit/PressableButtonGodot.tscn
- Toolkit/ToolkitText.cs
- Toolkit/ToolkitText.tscn
The `ToolkitText` class replaces `SimpleText` from `MREGodotRuntime`.
This patch removes the dependency of Runtime form Toolkit pacakges.
> toolkit: introduce text class for toolkit

- MREGodotRuntimeLib/Messaging/Commands/CommandManager.cs
In the latest version of Godot, the return value of `Godot.OS.GetTicksMsec` has
been changed. this causes type mismatch error. to fix this, the variable type of
`uint` is replaced with `ulong`.
> lib: fix build error on the latest version of Godot

- MREGodotRuntimeLib/Core/Actor.cs
`AttachmentComponent`'s parent is 'attach point' that is not children of actor.
Which means `AttachmentComponent` is not deleted event if the actor is deleted.
This patch deletes it with `tree_exited` signal of actor.
> lib: fix AttachmentComponent free issue.

- MREGodotRuntimeLib/Core/Actor.cs
- MREGodotRuntimeLib/Core/Collider.cs
When MRE is compiled with runtime into the same package, there are no
problems loading script via relative path. but, if you use MRE DLL that contains
compiled cs files, script is not loaded because there are no cs files.
I thought using relative path was the only way, but it turns out that i can get
script from an instance.
I hope it works the same as before.. i couldn't find any issues in my tests.
> lib: initialize actor via script instance instead of its relative file path

- MREGodotRuntime/Scripts/Tools/TargetTool.cs
If a node that `TargetBehavior` as a child, it's an Actor, so there is no need
to check it's an Actor type.
> runtime: remove unnecessary type check

- MREGodotRuntimeLib/Assets/AssetLoader.cs
It seems that `Node.Duplicate` isn't duplicate its reosurces.
If you have multiple actors with same prefab's id and you change an actor's
resouce, the other actor's resource will also change.
This is not the expected behavior.
To fix this issue, it duplicates resources of nodes at prefab creation time.
> lib: duplicate resources in prefab creation

- MREGodotRuntimeLib/Assets/AssetFetcher.cs
- MREGodotRuntimeLib/Assets/AssetLoader.cs
- MREGodotRuntimeLib/Util/Godot/GodotWebRequest.cs
Godot's HTTP API doesn't seem to work well in an asynchronous environment.
This replaces GodotWebRequest's implementation with UnityGLTF's one.
> lib: rewrite GodotWebRequest

- MREGodotRuntimeLib/Core/ColliderGeometry.cs
MRE uses a left hand coordinate system same as Unity Engine which means it has invert z-axis of godot. so, z-axis should be multiplied by a negative number.
> apply negative z-axis value of box collider position

- MREGodotRuntimeLib/API/MREApi.cs
- MREGodotRuntimeLib/App/MixedRealityExtensionApp.cs
- MREGodotRuntimeLib/Messaging/Commands/CommandManager.cs
- The patch also changes the way to store a plugin's type and instance in the dictionary.
- It allows clients to connect a server even when the server is found while clients running.
- It allows clients to re-connect a server after having a disconnection issue.
Co-authored-by: id213sin <id213sin@gmail.com>
> Download server's manifest after confirming server connection
